# Server Config
server.port=8081


# PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres_DB
spring.datasource.username=postgres
spring.datasource.password=postgres@25
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Run data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.expiration=3600000